### PR TITLE
Documentation tweaks

### PR DESCRIPTION
**Pull request by allaway**
*changed install_github to `remotes` as explained why here: https://twitter.com/bearloga/status/1235985861944184832
*fleshed out basic usage instructions and reorganized a bit to add some emphasis on how to use synapseclient with challengerutils/reticulate.

- [x] Did you reference the issue being addressed by number? (fixes #xxxx)
- [x] Did you run your tests locally (instructions [here](https://github.com/Sage-Bionetworks/challengerutils/blob/master/CONTRIBUTING.md)?
- [x] Did you add a good description about your changes or additions?

### CODE REVIEW

**Comment by allaway** [comment]
Also, the Contributing guidelines say to pull against develop, but it looks like I am merging all of the master changes into develop. What do you prefer?

**Comment by allaway** [comment]
For reviewing purposes, the only changes I made here are in the README.md, all the other changes are yours.

**Comment by thomasyu888** [comment]
Thanks for the contribution.  For now pulling into master is fine, but as soon as I start tagging releases, I want master branch to always mimic the latest stable release which is why I don't like develop as the default branch.

**Review by thomasyu888 — APPROVED** [review]

**Comment by allaway** [comment]
>which is why I don't like develop as the default branch.

I'm a little confused - if you set `develop` as the default branch, then developer PRs will default to be against the latest development version. 

For end users, you tell them to install using `remotes::install_github('Sage-Bionetworks/challengerutils@master') in the documentation, they will always install from the the latest tagged release (which will be master, right?) .

**Comment by thomasyu888** [comment]
@allaway That is true, but sometimes the "develop" branch is under construction.  Im just not a huge fan of the idea that when someone does a `git clone` it automatically puts them at the `default` branch.

**Comment by allaway** [comment]
An interesting, fair enough!

**Pull request merged**
